version: 3

networks:
  main:
    external: true

services:
  app:
    container_name: project
    image: node:latest
    working_dir: /usr/src/app
    restart: always
    command: bash -c "cd frontend && yarn start && cd .. && cd backend && yarn start:dev"
    ports:
      - "3333:3333"
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
    networks:
      - main
  mongo:
    container: project-mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/db/mongodb:/data/db
      - ./.docker/db/mongo-init.js:/docker-entrypoint-initdb.d/mmongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INIT_DB_DATABASE: project
    networks:
      - project
